# Generated by Django 3.2.25 on 2024-11-07 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20241107_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='pirce',
        ),
        migrations.AddField(
            model_name='rating',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price $'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1, help_text='Enter a rating between 1 and 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, verbose_name='What did you think??'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large'), ('W', 'Weird Milk')], max_length=1, null=True, verbose_name='Cup Size'),
        ),
    ]
