# Generated by Django 3.2.25 on 2024-11-07 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20241107_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='coffeeshop_tag',
            field=models.CharField(default='', max_length=100, verbose_name='Known for'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='coffeeshop_address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='coffeeshop_name',
            field=models.CharField(max_length=100, verbose_name='Coffee Shop Name'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='coffeeshop_status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], max_length=1, verbose_name='Still in business?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='coffeeshop',
            field=models.ForeignKey(limit_choices_to={'coffeeshop_status': 'A'}, on_delete=django.db.models.deletion.CASCADE, to='website.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price in dollars', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price $'),
        ),
    ]
