# Generated by Django 3.2.25 on 2024-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20241107_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='coffeeshop_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='coffeeshop_tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Known for'),
        ),
    ]
